name: Deploy PoC

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configurar Node.js y dependencias en la carpeta poc-frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
          
      - name: Install dependencies
        run: npm install
        working-directory: ./poc-frontend  # Establecer el directorio de trabajo

      - name: Build the app
        run: npm run build  # Cambia de 'dev' a 'build' para la producción
        working-directory: ./poc-frontend  # Establecer el directorio de trabajo

      # Configurar Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Subir el artefacto (apuntar a la carpeta donde está el index.html)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './poc-frontend/dist'  # Apunta a la carpeta donde está el index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
